apiVersion: v1
kind: Secret
metadata:
    name: {{ template "scdf.fullname" . }}-secret
    labels:
        app: {{ template "scdf.name" . }}
        component: server
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
type: Opaque
data:
 "dataflow.keystore.jks": |-
    {{ .Files.Get "config/dataflow.keystore" | b64enc }}
