apiVersion: {{ printf "%s/v1" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
    name: {{ include "scdf.fullname" . }}-svcmonitor
    namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
    labels:
        k8s-app: {{ template "scdf.name" . }}-server
spec:
    jobLabel: k8s-app
    selector:
        matchLabels:
            k8s-app: {{ template "scdf.name" . }}-server
    endpoints:
        - port: web
          honorLabels: true
          path: "/runtime/apps"
    namespaceSelector:
        any: true