apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scdf.fullname" . }}-server
  labels:
    app: {{ template "scdf.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yaml: |-
    server:
      port: {{ .Values.server.port }}
      ssl:
        enabled: {{ .Values.server.ssl.enabled }}
        key-alias: {{ .Values.server.ssl.key-alias }}
        key-store: "/data/secrets/keystore/"{{ .Values.server.ssl.key-store }}
        key-store-type: {{ .Values.server.ssl.key-store-type }}
        key-store-password: {{ .Values.server.ssl.key-store-password }}
        key-password: {{ .Values.server.ssl.key-password }}
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  {{ .Values.server.platformName }}:
                    limits:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{ .Values.deployer.resourceLimits.cpu }}
      datasource:
        url: 'jdbc:mysql://{{ template "scdf.database.host" . }}:{{ template "scdf.database.port" . }}/{{ template "scdf.database.dataflow" . }}'
        driverClassName: {{ template "scdf.database.driver" . }}
        username: {{ template "scdf.database.user" . }}
        password: {{ template "scdf.database.password" . }}
        testOnBorrow: true
        validationQuery: "SELECT 1"
