apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scdf.fullname" . }}-server
  labels:
    app: {{ template "scdf.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yaml: |-
    server:
      port: {{.Values.server.port}}
      ssl:
        enabled: {{ .Values.server.ssl.enable }}
        key-alias: {{ .Values.server.ssl.keyalias }}
        key-store: "{{ .Values.server.ssl.mountPath}}/{{ .Values.server.ssl.keystore}}"
        key-store-type: {{ .Values.server.ssl.keystoretype }}
        key-store-password: {{ .Values.server.ssl.keystorepassword }}
        key-password: {{ .Values.server.ssl.keypassword }}
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  {{ .Values.server.platformName }}
                    limits:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{ .Values.deployer.resourceLimits.cpu }}
                    requests:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{.Values.deployer.resourceLimits.cpu}}
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  {{ .Values.server.platformName }}
                    limits:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{ .Values.deployer.resourceLimits.cpu }}
      datasource:
        url: 'jdbc:mysql://${{ printf "{" }}{{ template "scdf.envrelease" . }}_MYSQL_SERVICE_HOST}:${{ printf "{" }}{{ template "scdf.envrelease" . }}_MYSQL_SERVICE_PORT}/{{ .Values.mysql.mysqlDatabase }}'
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: ${mysql-root-password}
        testOnBorrow: true
        validationQuery: "SELECT 1"