apiVersion: {{ printf "%s/v1" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
    name: {{ include "scdf.fullname" . }}-scdf-spring-app-svcmonitor
    namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
    labels:
        role: spring-app
spec:
    jobLabel: k8s-app
    selector:
        matchLabels:
            role: spring-app
    endpoints:
        - port: web
          honorLabels: true
          path: "/actuator/prometheus"
    namespaceSelector:
        any: true